### ISSUE TITLE
New York Districts Missing numbers

### ISSUE THREAD

**Issue by ezi321gc** [JeffreyBLewis/congressional-district-boundaries#7]
Hello I wanted to point out that the New York Districts for 73 to 78 are missing their districts number. When I click on it, it says that they are all 0th dirstricts.

**Comment by JeffreyBLewis** [comment]
It appears that what you are seeing is an artifact of the way that github renders geojson files.   During this period, NY had an at-large district (here numbered district 0).   It appears that whether this at-large district is rendered on top or underneath (some of) the numbered districts varies from page load to page load.   For areas of the state in which the browser has rendered the at-large district on top of the numbered district,  clicking on the map to display the associated metadata reveals the data associated with the at-large district instead of that associated with the numbered district that you are expecting to see.   The order in which the district shapes are rendered appears to be indeterminate.  On some page loads, I see what you see and other times I am shown (at least a few of) the numbered districts' metadata. I don't know of any way to address the situation.  

In any case, the district numbers are included in the underlying data as I have confirmed by pulling the geojson file into R and making the map below:

![image](https://user-images.githubusercontent.com/4761445/163687222-97900857-36cd-46cc-bd60-1aeb12faa706.png)
